=== libgraviton/graviton/src/Graviton/GeneratorBundle/Resources/schema/definition-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON definition schema",
  "description": "Schema for JSON definition validation",
  "type": "object",
  "properties": {
    "id": {
      "title": "Definition ID",
      "$ref": "#/definitions/collectionName"
    },
    "isSubDocument": {
      "title": "Is sub-document",
      "type": "boolean"
    },
    "title": {
      "title": "Definition title",
      "type": "string"
    },
    "description": {
      "title": "Definition description",
      "type": "string"
    },
    "service": {
      "title": "Service definition",
      "$ref": "#/definitions/service"
    },
    "target": {
      "title": "Target definition",
      "$ref": "#/definitions/target"
    },
    "source": {
      "title": "Source list",
      "type": "array",
      "items": {
        "$ref": "#/definitions/source"
      }
    },
    "loadPackage": {
      "title": "Package name",
      "type": "string"
    },
    "dependencies": {
      "title": "Definition dependencies",
      "type": "array",
      "items": {
        "$ref": "#/definitions/collectionName"
      }
    }
  },
  "required": [
    "id",
    "target"
  ],
  "definitions": {
    "collectionName": {
      "type": "string",
      "pattern": "^[A-Z][a-zA-Z0-9_]*$"
    },
    "fieldName": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*$"
    },
    "fieldExposedName": {
      "type": "string"
    },
    "fieldDefinitionName": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*(\\.(0\\.)?[a-zA-Z_][a-zA-Z0-9_]*)*$"
    },
    "fieldBasicType": {
      "enum": [
        "string",
        "varchar",
        "text",
        "int",
        "bigint",
        "float",
        "double",
        "decimal",
        "datetime",
        "boolean",
        "hash",
        "object",
        "extref"
      ]
    },
    "fieldUpperType": {
      "enum": [
        "STRING",
        "VARCHAR",
        "TEXT",
        "INT",
        "BIGINT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "DATETIME",
        "BOOLEAN",
        "HASH",
        "OBJECT",
        "EXTREF"
      ]
    },
    "fieldClassType": {
      "type": "string",
      "pattern": "^class:\\\\?[a-zA-Z_][a-zA-Z0-9_]*(\\\\[a-zA-Z_][a-zA-Z0-9_]*)*(\\[\\])?$"
    },
    "relationType": {
      "enum": [
        "embed",
        "ref"
      ]
    },
    "routerBase": {
      "type": "string",
      "pattern": "^\/?[a-z0-9_-]+(\/[a-z0-9_-]+)*\/?$"
    },

    "service": {
      "type": "object",
      "properties": {
        "readOnly": {
          "title": "Is service read-only",
          "type": "boolean"
        },
        "routerBase": {
          "title": "Router base path",
          "$ref": "#/definitions/routerBase"
        },
        "parent": {
          "title": "Parent service ID",
          "type": "string"
        },
        "baseController": {
          "title": "Base controller class",
          "type": "string"
        },
        "roles": {
          "title": "Role list",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "fixtureOrder": {
          "title": "Fixture order number",
          "type": "integer"
        },
        "fixtures": {
          "title": "Service fixtures",
          "type": "array",
          "items": {
            "$ref": "#/definitions/serviceFixture"
          }
        }
      },
      "additionalProperties": false
    },
    "serviceFixture": {
      "type": "object",
      "additionalProperties": true
    },

    "source": {
      "type": "object",
      "properties": {
        "type": {
          "title": "Source type",
          "$ref": "#/definitions/sourceType"
        },
        "params": {
          "title": "Source params",
          "$ref": "#/definitions/sourceParams"
        }
      },
      "required": [
        "type",
        "params"
      ],
      "additionalProperties": false
    },
    "sourceType": {
      "type": "string"
    },
    "sourceParams": {
      "type": "object",
      "properties": {},
      "additionalProperties": true
    },

    "target": {
      "type": "object",
      "properties": {
        "indexes": {
          "title": "Target indexes",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetIndex"
          }
        },
        "relations": {
          "title": "Target relations",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetRelation"
          }
        },
        "fields": {
          "title": "Target fields",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetField"
          }
        },
        "connectionName": {
          "title": "Connection name",
          "type": "string"
        },
        "collectionName": {
          "title": "Collection name",
          "$ref": "#/definitions/collectionName"
        },
        "sqlFile": {
          "title": "SQL file path",
          "type": "string"
        }
      },
      "required": [
        "fields"
      ],
      "additionalProperties": false
    },
    "targetIndex": {
      "type": "string"
    },
    "targetRelation": {
      "type": "object",
      "properties": {
        "type": {
          "title": "Relation type",
          "$ref": "#/definitions/relationType"
        },
        "collectionName": {
          "title": "Related collection name",
          "$ref": "#/definitions/collectionName"
        },
        "localProperty": {
          "title": "Local relation property",
          "$ref": "#/definitions/fieldDefinitionName"
        },
        "localValueField": {
          "title": "Local value field",
          "$ref": "#/definitions/fieldName"
        },
        "foreignProperty": {
          "title": "Foreign relation field",
          "$ref": "#/definitions/fieldName"
        }
      },
      "required": [
        "type",
        "localProperty"
      ],
      "additionalProperties": false
    },
    "targetField": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Field name",
          "$ref": "#/definitions/fieldDefinitionName"
        },
        "type": {
          "title": "Field type",
          "oneOf": [
            {"$ref": "#/definitions/fieldBasicType"},
            {"$ref": "#/definitions/fieldUpperType"},
            {"$ref": "#/definitions/fieldClassType"}
          ]
        },
        "exposeAs": {
          "title": "Field title",
          "$ref": "#/definitions/fieldExposedName"
        },
        "title": {
          "title": "Field title",
          "type": "string"
        },
        "description": {
          "title": "Field description",
          "type": "string"
        },
        "length": {
          "title": "Field length",
          "type": "integer",
          "minimum": 0
        },
        "readOnly": {
          "title": "Is field read-only",
          "type": "boolean"
        },
        "required": {
          "title": "Is field required",
          "type": "boolean"
        },
        "translatable": {
          "title": "Is field translatable",
          "type": "boolean"
        },
        "constraints": {
          "title": "Field constraints",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetFieldConstraint"
          }
        },
        "collection": {
          "title": "Allowed extref collections",
          "type": "array",
          "items": {
            "oneOf": [
              {"$ref": "#/definitions/collectionName"},
              {"enum": ["*"]}
            ]
          },
          "uniqueItems": true
        },
        "explodeBy": {
          "title": "For internal usage only",
          "type": "string"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "targetFieldConstraint": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Constraint name",
          "type": "string"
        },
        "options": {
          "title": "Constraint options",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetFieldConstraintOption"
          }
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "targetFieldConstraintOption": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Constraint option name",
          "type": "string"
        },
        "value": {
          "title": "Constraint option value",
          "type": "string"
        }
      },
      "required": [
        "name",
        "value"
      ],
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== libgraviton/graviton/src/Graviton/CoreBundle/Resources/definition/Mapping.json
{
    "id": "CoreMapping",
    "description": "A mapping from a module to several account types",
    "service": {
        "readOnly": false,
        "routerBase": "/core/mapping/",
        "fixtures": [
            {
                "from": {
                    "$ref": "http://localhost/core/module/admin-AdminRef"
                },
                "to": [
                    {
                        "$ref": "http://localhost/entity/code/accountType-1"
                    },
                    {
                        "$ref": "http://localhost/entity/code/accountType-2"
                    },
                    {
                        "$ref": "http://localhost/entity/code/accountType-3"
                    }
                ]
            },
            {
                "from": {
                    "$ref": "http://localhost/core/product/1"
                },
                "to": [
                    {
                      "$ref": "http://localhost/core/module/tablet-payAndSave"
                    },
                    {
                      "$ref": "http://localhost/core/module/tablet-realEstate"
                    }
                ]
            },
            {
                "from": {
                    "$ref": "http://localhost/i18n/language/de"
                },
                "to": [
                    {
                      "$ref": "http://localhost/person/customer/100"
                    }
                ]
            }
        ]
    },
    "target": {
        "indexes": [],
        "relations": [],
        "fields": [
            {
                "name": "from.ref",
                "type": "extref",
                "title": "Module Link",
                "description": "Link from a service",
                "exposeAs": "$ref",
                "required": true
            },
            {
                "name": "to.0.ref",
                "type": "extref",
                "title": "Entity codes",
                "description": "Array of service entries",
                "exposeAs": "$ref",
                "collection": ["Code"],
                "required": true
            }
        ]
    }
}

=== libgraviton/graviton/src/Graviton/CoreBundle/Resources/definition/EventStatusAction.json
{
  "id": "EventStatusAction",
  "description": "Action translation for worker events",
  "service": {
    "readOnly": false,
    "routerBase": "/event/action/",
    "fixtureOrder": 1,
    "fixtures": [
      {
        "id": "worker1-default1",
        "description": {
          "en": "Any core data load",
          "de": "Viele Kerndatenlast"
        }
      },
      {
        "id": "worker1-default2",
        "action": "core-config-create",
        "description": {
          "en": "Any core config data load",
          "de": "Viele Kerndatenlast config"
        }
      }
    ]
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "Unique id to be referred",
        "description": "Unique identifier and a short string identifying a single worker",
        "required": true
      },
      {
        "name": "description",
        "type": "string",
        "title": "Description",
        "description": "A translated description for action done",
        "required": false,
        "translatable" : true
      }
    ]
  }
}

=== libgraviton/graviton/src/Graviton/GeneratorBundle/Tests/Integration/Resources/Definition/TestB.json
{
    "id": "TestB",
    "description": "TestB",
    "service": {
        "routerBase": "/testb/"
    },
    "target": {
        "relations": [],
        "fields": [
            {
                "name": "abool",
                "type": "boolean",
                "required": true
            },
            {
                "name": "afield",
                "type": "varchar",
                "exposeAs": "$c"
            }
        ]
    }
}

=== libgraviton/graviton/src/Graviton/PersonBundle/Resources/definition/ConsultantContact.json
{
  "id": "ConsultantContact",
  "description": "An API allowing to contact consultants.",
  "service": {
    "readOnly": false,
    "routerBase": "/person/contact/consultant/",
    "baseController": "\\Graviton\\PersonBundle\\Controller\\ConsultantContactController",
    "fixtures": []
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier for an item."
      },
      {
        "name": "senderName",
        "type": "varchar",
        "title": "Sender name",
        "description": "Name of the contact initiator",
        "required": true
      },
      {
        "name": "senderEmail",
        "type": "varchar",
        "title": "Sender email",
        "description": "E-Mail of the sender"
      },
      {
        "name": "senderPhone",
        "type": "varchar",
        "title": "Sender Phone",
        "description": "Phone of the sender"
      },
      {
        "name": "comment",
        "type": "class:Graviton\\RestBundle\\Document\\PurifiedHtml",
        "title": "Comment",
        "description": "Comment",
        "required": true
      },
      {
        "name": "desiredContactDate",
        "type": "datetime",
        "title": "Desired Contact Date",
        "description": "When initiator wants consultant to contact"
      },
      {
        "name": "desiredContactTime",
        "type": "datetime",
        "title": "Desired Contact Date",
        "description": "When initiator wants consultant to contact"
      },
      {
        "name": "additionalData",
        "type": "object",
        "title": "Additional data",
        "description": "Additional submitted data"
      },
      {
        "name": "isProcessed",
        "type": "boolean",
        "title": "Is processed",
        "description": "true if the contact request has been sent."
      }
    ]
  }
}

=== libgraviton/graviton/src/Graviton/CoreBundle/Resources/definition/Module.json
{
  "id": "Module",
  "description": "A service containing modules that relate to apps",
  "service": {
    "readOnly": false,
    "routerBase": "/core/module/",
    "fixtures": [
      {
        "key": "realEstate",
        "appId": "tablet",
        "name": {
          "en": "Real Estate"
        },
        "path": "/module/realestate",
        "order": 1
      },
      {
        "key": "investment",
        "appId": "tablet",
        "name": {
          "en": "Investment"
        },
        "path": "/module/investment",
        "order": 2
      },
      {
        "key": "retirement",
        "appId": "tablet",
        "name": {
          "en": "Retirement"
        },
        "path": "/module/retirement",
        "order": 3
      },
      {
        "key": "requisition",
        "appId": "tablet",
        "name": {
          "en": "Requisition"
        },
        "path": "/module/requisition",
        "order": 4
      },
      {
        "key": "payAndSave",
        "appId": "tablet",
        "name": {
          "en": "Pay & Save"
        },
        "path": "/module/payandsave",
        "order": 5
      }
    ]
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier for an item."
      },
      {
        "name": "key",
        "type": "varchar",
        "title": "Key",
        "description": "A fixed string identifying this module.",
        "required": true
      },
      {
        "name": "appId",
        "type": "varchar",
        "title": "App ID",
        "description": "ID of an app this module relates to.",
        "required": true
      },
      {
        "name": "name",
        "type": "varchar",
        "title": "Name",
        "description": "Name of this module",
        "required": true,
        "translatable": true
      },
      {
        "name": "path",
        "type": "varchar",
        "title": "Path",
        "description": "A path this module points to."
      },
      {
        "name": "order",
        "type": "int",
        "title": "Order",
        "description": "Integer for sort order"
      }
    ]
  }
}

=== libgraviton/graviton/resources/definition/Showcase.json
{
    "id": "Showcase",
    "description": "A service showcasing all of our generator features",
    "service": {
        "readOnly": false,
        "baseController": "\\Graviton\\CoreBundle\\Controller\\ShowcaseExtensionController",
        "routerBase": "/hans/showcase/",
        "fixtures": [
            {
                "id": 500,
                "anotherInt": 6555488894525,
                "testField": {"en": "a test string"},
                "someOtherField": {"en": "another good ol' test string"},
                "aBoolean": false,
                "modificationDate": "1984-05-02T00:00:00Z",
                "contact": {
                    "type": "home",
                    "value": "joe@example.com",
                    "protocol": "mailto",
                    "$ref": "mailto:joe@example.com"
                },
                "contacts": [
                    {
                        "type": "business",
                        "value": "+41791456214",
                        "protocol": "tel",
                        "$ref": "tel:+41791456214"
                    },
                    {
                        "type": "home",
                        "value": "+41332434479",
                        "protocol": "tel",
                        "$ref": "tel:+41332434479"
                    },
                    {
                        "type": "home",
                        "value": "someuser",
                        "protocol": "skype",
                        "$ref": "skype:someuser"
                    }
                ],
                "contactCode": {
                    "someDate": "2012-12-21T00:00:00Z",
                    "text": {"en": "Ad mailing campaign 2012"}
                },
                "nestedArray": [
                    {"name": "element one"},
                    {"name": "element two"}
                ]

            },
            {
                "id": 600,
                "anotherInt": 544615898841,
                "testField": {"en": "some text"},
                "someOtherField": {"en": "this is a text from another field"},
                "aBoolean": true,
                "modificationDate": "2012-12-24T14:15:55Z",
                "contact": {
                    "type": "business",
                    "value": "dave@example-company.com",
                    "protocol": "mailto",
                    "$ref": "mailto:dave@example-company.com"
                },
                "contacts": [
                    {
                        "type": "home",
                        "value": "+41767845112",
                        "protocol": "tel",
                        "$ref": "tel:+41767845112"
                    },
                    {
                        "type": "home",
                        "value": "+41317415488",
                        "protocol": "tel",
                        "$ref": "tel:+41317415488"
                    },
                    {
                        "type": "business",
                        "value": "another@example.com",
                        "protocol": "jabber",
                        "$ref": "jabber:another@example.com"
                    }
                ],
                "contactCode": {
                    "someDate": "2014-06-30T11:45:31Z",
                    "text": {"en": "Phone call"}
                },
                "nestedArray": [
                    {"name": "array element one"},
                    {"name": "array element two"}
                ]

            }
        ]
    },
    "target": {
        "indexes": [],
        "relations": [],
        "fields": [
            {
                "name": "id",
                "type": "varchar",
                "description": "Unique identifier for an item."
            },
            {
                "name": "anotherInt",
                "type": "INT",
                "description": "Just a nice integer",
                "required": true
            },
            {
                "name": "testField",
                "type": "varchar",
                "title": "A testing title",
                "description": "A lengthy and detailed description.",
                "required": true,
                "translatable": true
            },
            {
                "name": "someOtherField",
                "type": "varchar",
                "title": "Another field",
                "description": "A very nice field",
                "translatable": true
            },
            {
                "name": "aBoolean",
                "type": "boolean",
                "title": "Some boolean",
                "description": "Everybody likes a good ol' bool",
                "required": true
            },
            {
                "name": "modificationDate",
                "type": "datetime",
                "title": "An important date",
                "description": "Don't forget to save the date"
            },
            {
                "name": "contact",
                "type": "class:Graviton\\PersonBundle\\Document\\PersonContact",
                "title": "A single contact element",
                "description": "How to contact someone..",
                "required": false
            },
            {
                "name": "contacts",
                "type": "class:Graviton\\PersonBundle\\Document\\PersonContact[]",
                "title": "An array of contact elements..",
                "description": "Other ways to contact someone.."
            },
            {
                "name": "contactCode.someDate",
                "type": "datetime",
                "title": "Another datetime",
                "description": "Who doesn't like a datetime??"
            },
            {
                "name": "contactCode.text",
                "type": "varchar",
                "translatable": true,
                "required": true,
                "title": "Meaning of the code",
                "description": "Some text to the code.."
            },
            {
                "name": "nestedArray.0.name",
                "type": "varchar",
                "title": "Name of nested array",
                "description": "Some text"
            }
        ]
    }
}
