=== libgraviton/graviton/src/Graviton/GeneratorBundle/Resources/schema/definition-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON definition schema",
  "description": "Schema for JSON definition validation",
  "type": "object",
  "properties": {
    "id": {
      "title": "Definition ID",
      "$ref": "#/definitions/collectionName"
    },
    "isSubDocument": {
      "title": "Is sub-document",
      "type": "boolean"
    },
    "title": {
      "title": "Definition title",
      "type": "string"
    },
    "description": {
      "title": "Definition description",
      "type": "string"
    },
    "service": {
      "title": "Service definition",
      "$ref": "#/definitions/service"
    },
    "target": {
      "title": "Target definition",
      "$ref": "#/definitions/target"
    },
    "source": {
      "title": "Source list",
      "type": "array",
      "items": {
        "$ref": "#/definitions/source"
      }
    },
    "loadPackage": {
      "title": "Package name",
      "type": "string"
    },
    "dependencies": {
      "title": "Definition dependencies",
      "type": "array",
      "items": {
        "$ref": "#/definitions/collectionName"
      }
    }
  },
  "required": [
    "id",
    "target"
  ],
  "definitions": {
    "collectionName": {
      "type": "string",
      "pattern": "^[A-Z][a-zA-Z0-9_]*$"
    },
    "fieldName": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*$"
    },
    "fieldExposedName": {
      "type": "string"
    },
    "fieldDefinitionName": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*(\\.(0\\.)?[a-zA-Z_][a-zA-Z0-9_]*)*$"
    },
    "fieldBasicType": {
      "enum": [
        "string",
        "varchar",
        "text",
        "int",
        "bigint",
        "float",
        "double",
        "decimal",
        "datetime",
        "boolean",
        "hash",
        "object",
        "extref"
      ]
    },
    "fieldUpperType": {
      "enum": [
        "STRING",
        "VARCHAR",
        "TEXT",
        "INT",
        "BIGINT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "DATETIME",
        "BOOLEAN",
        "HASH",
        "OBJECT",
        "EXTREF"
      ]
    },
    "fieldClassType": {
      "type": "string",
      "pattern": "^class:\\\\?[a-zA-Z_][a-zA-Z0-9_]*(\\\\[a-zA-Z_][a-zA-Z0-9_]*)*(\\[\\])?$"
    },
    "relationType": {
      "enum": [
        "embed",
        "ref"
      ]
    },
    "routerBase": {
      "type": "string",
      "pattern": "^\/?[a-z0-9_-]+(\/[a-z0-9_-]+)*\/?$"
    },

    "service": {
      "type": "object",
      "properties": {
        "readOnly": {
          "title": "Is service read-only",
          "type": "boolean"
        },
        "routerBase": {
          "title": "Router base path",
          "$ref": "#/definitions/routerBase"
        },
        "parent": {
          "title": "Parent service ID",
          "type": "string"
        },
        "baseController": {
          "title": "Base controller class",
          "type": "string"
        },
        "roles": {
          "title": "Role list",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "fixtureOrder": {
          "title": "Fixture order number",
          "type": "integer"
        },
        "fixtures": {
          "title": "Service fixtures",
          "type": "array",
          "items": {
            "$ref": "#/definitions/serviceFixture"
          }
        }
      },
      "additionalProperties": false
    },
    "serviceFixture": {
      "type": "object",
      "additionalProperties": true
    },

    "source": {
      "type": "object",
      "properties": {
        "type": {
          "title": "Source type",
          "$ref": "#/definitions/sourceType"
        },
        "params": {
          "title": "Source params",
          "$ref": "#/definitions/sourceParams"
        }
      },
      "required": [
        "type",
        "params"
      ],
      "additionalProperties": false
    },
    "sourceType": {
      "type": "string"
    },
    "sourceParams": {
      "type": "object",
      "properties": {},
      "additionalProperties": true
    },

    "target": {
      "type": "object",
      "properties": {
        "indexes": {
          "title": "Target indexes",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetIndex"
          }
        },
        "relations": {
          "title": "Target relations",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetRelation"
          }
        },
        "fields": {
          "title": "Target fields",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetField"
          }
        },
        "connectionName": {
          "title": "Connection name",
          "type": "string"
        },
        "collectionName": {
          "title": "Collection name",
          "$ref": "#/definitions/collectionName"
        },
        "sqlFile": {
          "title": "SQL file path",
          "type": "string"
        }
      },
      "required": [
        "fields"
      ],
      "additionalProperties": false
    },
    "targetIndex": {
      "type": "string"
    },
    "targetRelation": {
      "type": "object",
      "properties": {
        "type": {
          "title": "Relation type",
          "$ref": "#/definitions/relationType"
        },
        "collectionName": {
          "title": "Related collection name",
          "$ref": "#/definitions/collectionName"
        },
        "localProperty": {
          "title": "Local relation property",
          "$ref": "#/definitions/fieldDefinitionName"
        },
        "localValueField": {
          "title": "Local value field",
          "$ref": "#/definitions/fieldName"
        },
        "foreignProperty": {
          "title": "Foreign relation field",
          "$ref": "#/definitions/fieldName"
        }
      },
      "required": [
        "type",
        "localProperty"
      ],
      "additionalProperties": false
    },
    "targetField": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Field name",
          "$ref": "#/definitions/fieldDefinitionName"
        },
        "type": {
          "title": "Field type",
          "oneOf": [
            {"$ref": "#/definitions/fieldBasicType"},
            {"$ref": "#/definitions/fieldUpperType"},
            {"$ref": "#/definitions/fieldClassType"}
          ]
        },
        "exposeAs": {
          "title": "Field title",
          "$ref": "#/definitions/fieldExposedName"
        },
        "title": {
          "title": "Field title",
          "type": "string"
        },
        "description": {
          "title": "Field description",
          "type": "string"
        },
        "length": {
          "title": "Field length",
          "type": "integer",
          "minimum": 0
        },
        "readOnly": {
          "title": "Is field read-only",
          "type": "boolean"
        },
        "required": {
          "title": "Is field required",
          "type": "boolean"
        },
        "translatable": {
          "title": "Is field translatable",
          "type": "boolean"
        },
        "constraints": {
          "title": "Field constraints",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetFieldConstraint"
          }
        },
        "collection": {
          "title": "Allowed extref collections",
          "type": "array",
          "items": {
            "oneOf": [
              {"$ref": "#/definitions/collectionName"},
              {"enum": ["*"]}
            ]
          },
          "uniqueItems": true
        },
        "explodeBy": {
          "title": "For internal usage only",
          "type": "string"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "targetFieldConstraint": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Constraint name",
          "type": "string"
        },
        "options": {
          "title": "Constraint options",
          "type": "array",
          "items": {
            "$ref": "#/definitions/targetFieldConstraintOption"
          }
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "targetFieldConstraintOption": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Constraint option name",
          "type": "string"
        },
        "value": {
          "title": "Constraint option value",
          "type": "string"
        }
      },
      "required": [
        "name",
        "value"
      ],
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== libgraviton/graviton/src/Graviton/CoreBundle/Resources/definition/Config.json
{
    "id": "Config",
    "description": "A service containing to admin general configuration parameters.",
    "service": {
        "readOnly": false,
        "routerBase": "/core/config/",
        "baseController": "\\Graviton\\CoreBundle\\Controller\\ConfigController",
        "fixtures": [
            {
                "id": "123j12j3j123j12j3",
                "key": "random key",
                "app_id": "$ref tablet",
                "defaultValue": "Hello World!",
                "actualValue": "Welcome World!"
            }
        ]
    },
    "target": {
        "indexes": [],
        "relations": [],
        "fields": [
            {
                "name": "id",
                "type": "varchar",
                "title": "ID",
                "description": "Unique identifier for an item.",
                "required": true
            },
            {
                "name": "key",
                "type": "varchar",
                "title": "Key",
                "description": "A fixed string identifying this module.",
                "required": true
            },
            {
                "name": "app_id",
                "type": "extref",
                "title": "Application-Link",
                "description": "Link to a application.",
                "exposeAs": "$ref",
                "required": true
            },
            {
                "name": "defaultValue",
                "type": "varchar",
                "title": "Default value",
                "description": "Name of this module"
            },
            {
                "name": "actualValue",
                "type": "varchar",
                "title": "Current value",
                "description": "The current value of the parameter.",
                "required": true
            }
        ]
    }
}

=== libgraviton/graviton/src/Graviton/CoreBundle/Resources/definition/ExternalLinks.json
{
  "id": "ExternalLinks",
  "description": "A service containing external links",
  "service": {
    "readOnly": false,
    "routerBase": "/core/external-link/",
    "fixtures": []
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier of an external link"
      },
      {
        "name": "name",
        "type": "varchar",
        "title": "Name",
        "description": "Name of the external link",
        "translatable": true
      },
      {
        "name": "url",
        "type": "varchar",
        "title": "URL",
        "description": "The URL",
        "constraints": [
          {
            "name": "Url",
            "options": [{"name": "message", "value":"The url '{{ value }}' is not a valid url"}]
          }
        ]
      },
      {
        "name": "order",
        "type": "int",
        "title": "Order",
        "description": "The order index"
      },
      {
        "name": "group",
        "type": "varchar",
        "title": "Group",
        "description": "A field to build groups of links."
      }
    ]
  }
}

=== libgraviton/graviton/src/Graviton/CoreBundle/Resources/definition/App.json
{
  "id": "App",
  "description": "A graviton based app.",
  "service": {
    "readOnly": false,
    "routerBase": "/core/app/",
    "fixtures": [
      {
        "id": "tablet",
        "title": {"en": "Tablet"},
        "showInMenu": true,
        "order": 1
      },
      {
        "id": "admin",
        "title": {"en": "Administration"},
        "showInMenu": true,
        "order": 2
      }
    ]
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier for an app.",
        "required": true
      },
      {
        "name": "title",
        "type": "varchar",
        "title": "Title",
        "description": "Display name for an app.",
        "required": true,
        "translatable": true
      },
      {
        "name": "showInMenu",
        "type": "boolean",
        "title": "Show in Menu",
        "description": "Define if an app should be exposed on the top level menu.",
        "required": true
      },
      {
        "name": "order",
        "type": "int",
        "title": "Order",
        "description": "A sorting order field.",
        "required": true
      }
    ]
  }
}

=== libgraviton/graviton/src/Graviton/RabbitMqBundle/Resources/definition/EventWorker.json
{
  "id": "EventWorker",
  "description": "A service giving the possibility for EventWorkers to register themselves.",
  "service": {
    "readOnly": false,
    "routerBase": "/event/worker/",
    "fixtures": [
      {
        "id": "worker1",
        "subscription": [
          {
            "event": "document.core.app.*"
          },
          {
            "event": "document.core.config.*"
          }
        ]
      },
      {
        "id": "worker2",
        "subscription": [
          {
            "event": "document.core.app.*"
          }
        ]
      }
    ]
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "Worker ID",
        "description": "Unique identifier and a short string identifying a single worker",
        "required": true
      },
      {
        "name": "subscription.0.event",
        "type": "string",
        "title": "Subscriptions",
        "description": "An array of strings containing event names this worker should be notified of",
        "required": true
      }
    ]
  }
}

=== libgraviton/graviton/src/Graviton/GeneratorBundle/Tests/Integration/Resources/Definition/TestA.json
{
    "id": "TestA",
    "description": "TestA",
    "service": {
        "routerBase": "/testa/"
    },
    "target": {
        "relations": [
            {
                "type": "embed",
                "localProperty": "testEmbed"
            }
        ],
        "fields": [
            {
                "name": "id",
                "type": "varchar",
                "description": "Unique identifier for an item."
            },
            {
                "name": "anotherInt",
                "type": "INT",
                "description": "Just a nice integer",
                "required": true
            },
            {
                "name": "testField",
                "type": "varchar",
                "required": true,
                "translatable": true
            },
            {
                "name": "embed.fieldA",
                "type": "varchar"
            },
            {
                "name": "embed.fieldB",
                "type": "varchar"
            },
            {
                "name": "testbRef",
                "type": "class:GravitonDyn\\TestBBundle\\Document\\TestB"
            },
            {
                "name": "testEmbed",
                "type": "class:GravitonDyn\\TestBBundle\\Document\\TestB"
            },
            {
                "name": "extref.ref",
                "exposeAs": "$ref",
                "type": "extref"
            }
        ]
    }
}

=== libgraviton/graviton/src/Graviton/GeneratorBundle/Tests/Resources/Definition/testDefinition.json
{
    "id": "TestDefinition",
    "description": "Whatever test",
    "service": {
        "routerBase": "/test/definition/",
        "roles": ["GRAVITON_USER"],
        "fixtures": [
            {
                "id": 500,
                "anotherInt": 6555488894525,
                "testField": {"en": "a test string"}
            }
        ]
    },
    "target": {
        "relations": [],
        "fields": [
            {
                "name": "id",
                "type": "varchar",
                "description": "Unique identifier for an item."
            },
            {
                "name": "anotherInt",
                "type": "INT",
                "description": "Just a nice integer",
                "required": true
            },
            {
                "name": "testField",
                "type": "varchar",
                "title": "A testing title",
                "description": "A lengthy and detailed description.",
                "required": true,
                "translatable": true
            }
        ]
    }
}

=== libgraviton/graviton/src/Graviton/GeneratorBundle/Tests/Definition/resources/test-minimal-relations.json
{
  "id": "Relations",
  "description": "Relations",
  "isSubDocument": true,
  "service": {
    "routerBase": "/hans/showcase",
    "readOnly": true
  },
  "target": {
    "relations": [
      {
        "type": "embed",
        "collectionName": "Entity1",
        "localProperty": "anotherInt",
        "localValueField": "anotherInt",
        "foreignProperty": "_id"
      },
      {
        "type": "ref",
        "collectionName": "Entity2",
        "localProperty": "someFloatyDouble",
        "localValueField": "someFloatyDouble"
      }
    ],
    "fields": [
      {
        "name": "anotherInt",
        "type": "INT",
        "description": "Just a nice integer",
        "required": true
      },
      {
        "name": "someFloatyDouble",
        "type": "double",
        "title": "Floaty double",
        "description": "An int with precision.."
      }
    ]
  }
}

=== libgraviton/graviton/src/Graviton/RabbitMqBundle/Resources/definition/EventStatus.json
{
  "id": "EventStatus",
  "description": "A service providing resources providing status' on events subscribed by workers.",
  "service": {
    "readOnly": false,
    "routerBase": "/event/status/"
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier"
      },
      {
        "name": "createDate",
        "type": "datetime",
        "title": "Creation date",
        "description": "Creation date",
        "readOnly": true
      },
      {
        "name": "eventName",
        "type": "varchar",
        "title": "Event Name",
        "description": "Name of the created event",
        "readOnly": true
      },
      {
        "name": "status.0.workerId",
        "type": "string",
        "title": "Worker ID",
        "description": "ID of a worker",
        "required": true
      },
      {
        "name": "status.0.status",
        "type": "string",
        "title": "Status",
        "description": "A string representing the status (opened, working, failed, done)",
        "required": true,
        "constraints": [
          {
            "name": "Graviton\\RabbitMqBundle\\Validator\\Constraints\\ValidStatus"
          }
        ]
      },
      {
        "name": "information",
        "type": "hash",
        "title": "Information",
        "description": "An array of objects containing worker information",
        "required": false
      },
      {
        "name": "information.0.workerId",
        "type": "string",
        "title": "Worker ID",
        "description": "ID of a worker",
        "required": true
      },
      {
        "name": "information.0.type",
        "type": "string",
        "title": "Information type",
        "description": "The type of information the worker published",
        "required": true,
        "constraints": [
          {
            "name": "Graviton\\RabbitMqBundle\\Validator\\Constraints\\ValidInformationType"
          }
        ]
      },
      {
        "name": "information.0.content",
        "type": "string",
        "title": "Worker output",
        "description": "A place where a worker can put any information content",
        "required": true
      },
      {
        "name": "information.0.ref",
        "type": "string",
        "exposeAs": "$ref",
        "title": "Ref",
        "collection": ["*"],
        "description": "An optional $ref that can be written by the worker",
        "required": false
      }
    ]
  }
}
